### ISSUE TITLE
모니터링 설정

### ISSUE THREAD

**Issue by Irisation23** [2Jo-Logistics-Management/logistics-management#40]
## Overview

- 액추에이터 설정 추가
- 프로메테우스 설정 추가
- 그라파나 설정 추가

---

## To-Do

- [ ] 액추에이터 의존성 추가
- [ ] 액추에이터 설정 추가
- [ ] 프로메테우스 의존성 추가
- [ ] 프로메테우스 설정 추가

---

### Reference

> 참조 자료 및 링크
> [스프링 부트 액추에이터 사용기](https://incheol-jung.gitbook.io/docs/study/srping-in-action-5th/chap-16.)
> [Swagger 설정과 acurator 설정 동시에 하면 오류가 발생해서 해결 할 때 참고한 블로그](https://velog.io/@dirn0568/SpringBoot-actuator%EC%99%80-Swagger%EB%A5%BC-%EA%B0%99%EC%9D%B4-%EC%93%B8%EB%95%8Corg.springframework.context.ApplicationContextException-Failed-to-start-bean-documentationPluginsBootstrapper-nested-exception-is-java.lang.NullPointerException-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0%EB%B2%95)
