### ISSUE TITLE
메인 페이지 화면 개발

### ISSUE THREAD

**Issue by ap9407** [2Jo-Logistics-Management/logistics-management#56]
## Overview

- 발주 state 개발
- 창고 top5 개발
- 발주 입고 카운트 개발

---

## To-Do

- [ ] 발주 준비, 진행, 완료 개발
- [ ] 창고 top5 개발
- [ ] 발주 카운트, 입고 카운트 개발

---

// 이슈 해결에 참조한 링크가 있다면 작성 해 주세요.
### Reference

> 참조 자료 및 링크
> `[참조한 링크](홈페이지 명을 입력 해 주세요.)`
